### ISSUE TITLE
How to change the quantizer model.

### ISSUE THREAD

**Issue by HobisPL** [rsxdalv/tts-generation-webui#17] opened 2023-05-28 11:44 UTC
I encountered an error when trying to use my own quantizer. I have been testing this model, and it works, but I don't know where to add it in your code so that I can use my own. The one you provided only works in English. So, I placed it in the folder where the hubert models are and renamed it as "tokenizer," but I'm getting an error:

```
RuntimeError: Error(s) in loading state_dict for CustomTokenizer:
Unexpected key(s) in state_dict: "intermediate.weight", "intermediate.bias".
size mismatch for fc.weight: copying a param with shape torch.Size([10000, 4096]) from checkpoint, the shape in the current model is torch.Size([10000, 1024])
```

Using the code below, everything works fine.
```
import os
import torchaudio
import torch
import numpy as np

from hubert.hubert_manager import HuBERTManager
from hubert.pre_kmeans_hubert import CustomHubert
from hubert.customtokenizer import CustomTokenizer
from encodec import EncodecModel
from encodec.utils import convert_audio

hubert_model = CustomHubert(checkpoint_path='data/models/hubert/hubert.pt')

wav, sr = torchaudio.load('audio.wav')
if wav.shape[0] == 2:
    wav = wav.mean(0, keepdim=True)
semantic_vectors = hubert_model.forward(wav, input_sample_hz=sr)
tokenizer = CustomTokenizer.load_from_checkpoint('data/models/hubert/tokenizer.pth')
semantic_tokens = tokenizer.get_token(semantic_vectors)
model = EncodecModel.encodec_model_24khz()
model.set_target_bandwidth(6.0)
wav, sr = torchaudio.load('audio.wav')
wav = convert_audio(wav, sr, model.sample_rate, model.channels)
wav = wav.unsqueeze(0)
with torch.no_grad():
    encoded_frames = model.encode(wav)
codes = torch.cat([encoded[0] for encoded in encoded_frames], dim=-1).squeeze()
fine_prompt = codes
coarse_prompt = fine_prompt[:2, :]
np.savez('helloWorld.npz', semantic_prompt=semantic_tokens, fine_prompt=fine_prompt, coarse_prompt=coarse_prompt)
```

**Comment by rsxdalv** [comment] 2023-05-28 12:56
I can try to check it in maybe 8 or so hours. Meanwhile, is your quantizer
available publicly? Then I can test it.

**Comment by HobisPL** [comment] 2023-05-28 14:54
Hobis/bark-voice-cloning-polish-HuBERT-quantizer

**Comment by rsxdalv** [comment] 2023-05-28 19:04
I'll test it out, I suspect it might be due to me not updating the hubert repo yet

**Comment by rsxdalv** [comment] 2023-05-29 09:18
Yes, I needed multiple updates. I was able to reproduce the same errors and fix them.

(You can probably reuse your existing installation, but let me know if it does not work)
In order to get it to work use the latest installer v3.1 https://github.com/rsxdalv/one-click-installers-tts/releases/tag/v3.1 (if you cloned the installer you may simply `git pull`)
Then run `update` cmd/sh 
Then try voice cloning. 

Once you are all set, please close this issue.

Also, if you'd need to switch between multiple voice cloning tokenizers in the UI, please open a separate issue.

**Comment by HobisPL** [comment] 2023-05-29 18:38
Okay, now it works, thanks.

**Closed** 2023-05-29 18:39 UTC
